# Generated by Django 3.2.9 on 2022-07-24 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='follow_button',
        ),
        migrations.RemoveField(
            model_name='saved_post',
            name='posts',
        ),
        migrations.RemoveField(
            model_name='saved_post',
            name='user',
        ),
        migrations.DeleteModel(
            name='like_post',
        ),
        migrations.DeleteModel(
            name='saved_post',
        ),
    ]
